cmd_/mydata/linux/tools/objtool/arch/x86/decode.o := gcc -Wp,-MD,/mydata/linux/tools/objtool/arch/x86/.decode.o.d -Wp,-MT,/mydata/linux/tools/objtool/arch/x86/decode.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wno-type-limits -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wno-nested-externs -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I ./scripts/include -g -I/mydata/linux/tools/include -I/mydata/linux/tools/include/uapi -I/mydata/linux/tools/arch/x86/include/uapi -I/mydata/linux/tools/arch/x86/include -I/mydata/linux/tools/objtool/include -I/mydata/linux/tools/objtool/arch/x86/include -I/mydata/linux/tools/objtool/libsubcmd/include -D"BUILD_STR(s)=$(pound)s" -I/mydata/linux/tools/objtool/arch/x86/lib -c -o /mydata/linux/tools/objtool/arch/x86/decode.o arch/x86/decode.c

source_/mydata/linux/tools/objtool/arch/x86/decode.o := arch/x86/decode.c

deps_/mydata/linux/tools/objtool/arch/x86/decode.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/timesize.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/time64.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/floatn.h \
  /usr/include/x86_64-linux-gnu/bits/floatn-common.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endianness.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/x86_64-linux-gnu/bits/atomic_wide_counter.h \
  /usr/include/x86_64-linux-gnu/bits/struct_mutex.h \
  /usr/include/x86_64-linux-gnu/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib.h \
  /mydata/linux/tools/arch/x86/include/asm/insn.h \
  /usr/include/x86_64-linux-gnu/asm/byteorder.h \
  /usr/include/linux/byteorder/little_endian.h \
  /mydata/linux/tools/include/uapi/linux/stddef.h \
  /mydata/linux/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdbool.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /mydata/linux/tools/include/uapi/asm/bitsperlong.h \
  /mydata/linux/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /mydata/linux/tools/include/asm-generic/bitsperlong.h \
  /mydata/linux/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/linux/swab.h \
  /usr/include/x86_64-linux-gnu/asm/swab.h \
  /mydata/linux/tools/arch/x86/include/asm/inat.h \
  /mydata/linux/tools/arch/x86/include/asm/inat_types.h \
  arch/x86/../../../arch/x86/lib/inat.c \
  arch/x86/../../../arch/x86/lib/../include/asm/insn.h \
  /mydata/linux/tools/objtool/arch/x86/lib/inat-tables.c \
  arch/x86/../../../arch/x86/lib/insn.c \
  /mydata/linux/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /mydata/linux/tools/include/linux/build_bug.h \
  /mydata/linux/tools/include/linux/compiler.h \
  /mydata/linux/tools/include/linux/compiler_types.h \
  /mydata/linux/tools/include/linux/compiler-gcc.h \
  /mydata/linux/tools/include/linux/math.h \
  /mydata/linux/tools/include/linux/panic.h \
  /usr/include/byteswap.h \
  /mydata/linux/tools/include/linux/container_of.h \
  /usr/include/string.h \
  /usr/include/x86_64-linux-gnu/bits/types/locale_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/x86_64-linux-gnu/bits/strings_fortified.h \
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h \
  arch/x86/../../../arch/x86/lib/../include/asm/inat.h \
  /mydata/linux/tools/include/linux/unaligned.h \
  /mydata/linux/tools/include/vdso/unaligned.h \
  /usr/include/linux/errno.h \
  /mydata/linux/tools/include/uapi/asm/errno.h \
  /mydata/linux/tools/arch/x86/include/uapi/asm/errno.h \
  /mydata/linux/tools/include/uapi/asm-generic/errno.h \
  /mydata/linux/tools/include/uapi/asm-generic/errno-base.h \
  /mydata/linux/tools/include/linux/kconfig.h \
  arch/x86/../../../arch/x86/lib/../include/asm/emulate_prefix.h \
  /mydata/linux/tools/arch/x86/include/asm/nops.h \
  /mydata/linux/tools/arch/x86/include/asm/asm.h \
  /mydata/linux/tools/include/linux/stringify.h \
  /mydata/linux/tools/arch/x86/include/asm/orc_types.h \
  /mydata/linux/tools/objtool/include/objtool/check.h \
  /mydata/linux/tools/objtool/include/objtool/cfi.h \
  /mydata/linux/tools/objtool/arch/x86/include/arch/cfi_regs.h \
  /mydata/linux/tools/include/linux/list.h \
  /mydata/linux/tools/include/linux/poison.h \
  /mydata/linux/tools/objtool/include/objtool/arch.h \
  /mydata/linux/tools/objtool/include/objtool/objtool.h \
  /mydata/linux/tools/include/linux/hashtable.h \
  /mydata/linux/tools/include/linux/bitops.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
  /usr/include/x86_64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/x86_64-linux-gnu/bits/pthread_stack_min-dynamic.h \
  /usr/include/x86_64-linux-gnu/bits/pthread_stack_min.h \
  /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
  /mydata/linux/tools/include/linux/bits.h \
  /mydata/linux/tools/include/linux/const.h \
  /mydata/linux/tools/include/vdso/const.h \
  /mydata/linux/tools/include/uapi/linux/const.h \
  /mydata/linux/tools/include/vdso/bits.h \
  /mydata/linux/tools/include/uapi/linux/bits.h \
  /mydata/linux/tools/include/linux/overflow.h \
  /mydata/linux/tools/include/asm-generic/bitops.h \
  /mydata/linux/tools/include/asm-generic/bitops/__ffs.h \
  /mydata/linux/tools/include/asm-generic/bitops/__ffz.h \
  /mydata/linux/tools/include/asm-generic/bitops/fls.h \
  /mydata/linux/tools/include/asm-generic/bitops/__fls.h \
  /mydata/linux/tools/include/asm-generic/bitops/fls64.h \
  /mydata/linux/tools/include/asm-generic/bitops/hweight.h \
  /mydata/linux/tools/include/asm-generic/bitops/arch_hweight.h \
  /mydata/linux/tools/include/asm-generic/bitops/const_hweight.h \
  /mydata/linux/tools/include/asm-generic/bitops/atomic.h \
  /mydata/linux/tools/include/asm-generic/bitops/non-atomic.h \
  /mydata/linux/tools/include/linux/hash.h \
  /mydata/linux/tools/include/linux/log2.h \
  /mydata/linux/tools/objtool/include/objtool/elf.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/elf.h \
  /mydata/linux/tools/include/linux/rbtree.h \
  /mydata/linux/tools/include/linux/jhash.h \
  /mydata/linux/tools/include/linux/unaligned/packed_struct.h \
  /mydata/linux/tools/objtool/arch/x86/include/arch/elf.h \
  /mydata/linux/tools/objtool/include/objtool/warn.h \
  /usr/include/x86_64-linux-gnu/sys/stat.h \
  /usr/include/x86_64-linux-gnu/bits/stat.h \
  /usr/include/x86_64-linux-gnu/bits/struct_stat.h \
  /usr/include/fcntl.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl-linux.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl2.h \
  /usr/include/errno.h \
  /usr/include/x86_64-linux-gnu/bits/errno.h \
  /mydata/linux/tools/objtool/include/objtool/builtin.h \
  /mydata/linux/tools/objtool/libsubcmd/include/subcmd/parse-options.h \
  /mydata/linux/tools/objtool/include/objtool/endianness.h \

/mydata/linux/tools/objtool/arch/x86/decode.o: $(deps_/mydata/linux/tools/objtool/arch/x86/decode.o)

$(deps_/mydata/linux/tools/objtool/arch/x86/decode.o):
